### ISSUE TITLE
A full demo with a file upload field

### ISSUE THREAD

**Issue by azmeuk** [ValentinH/svelte-easy-crop#15]
Congratulations for this component.

I just thought it would be really appealing to show the component in a real world situation with a file upload field:
- the user chooses a picture
- the user crops the picture
- the user sends the form (with the cropped picture)

What do you think?

**Comment by ValentinH** [comment]
I agree that this would be a great demo. To be honest, I'm not using Svelte anymore so I'd not be super efficient building such a demo.

If someone is interested, we could do a demo similar to this React one: https://codesandbox.io/s/y09komm059

**Comment by azmeuk** [comment]
Thank you for your answer. Does it mean this component is unmaintained?

**Comment by ValentinH** [comment]
I aim to answer to issues and manage pull requests but I'm not actively working on this package.

**Comment by oscarhermoso** [comment]
Here's something thrown together pretty quickly. Hopefully inspires someone to take it another step forward 🐕

https://svelte.dev/repl/11303854cb6247ae99514acad96190b6?version=3.42.4

**Comment by ValentinH** [comment]
Thanks, I added this to the Readme 🚀
