### ISSUE TITLE
Add a slider to control the zoom

### ISSUE THREAD

**Issue by hubert-ix** [ValentinH/svelte-easy-crop#18]
It's a feature request, I suppose, but it would be very useful to add an optional slider in order to control the zoom (there is one on the React version). Otherwise the component is not usable on laptops, since there is no mouse wheel.

**Comment by ValentinH** [comment]
A slider could be added outside of this library as the zoom value is controlled by  the parent controller.

However, the zoom should work on laptops, even without a wheel, by using the 2-fingers gesture.

**Comment by hubert-ix** [comment]
That's a good point, I've tried adding a slider outside of the component and binding it to the zoom value, and it works great.
