### ISSUE TITLE
Ability to control the colour, thickness and line type of the grid

### ISSUE THREAD

**Issue by cpwood** [ValentinH/svelte-easy-crop#24]
The ability to control the colour, thickness and line type (solid, dotted, dashed) via properties on the `<Cropper>` would be useful. 

For my implementation, I've worked around this by turning off the out-of-the-box grid and then providing my own CSS, but a simpler way of influencing this would be a welcome feature.

Many thanks!

**Comment by ValentinH** [comment]
I think that you should already be able to implement a custom grid by hiding the default one (`showGrid` option) and add your styles with the `cropperArea` classname.

**Comment by cpwood** [comment]
Yes - as I say, that's what I did, but it required me to dig into the source code to figure out how to do it. A more readily apparent option would be helpful, but I agree, it is already possible.

**Comment by ValentinH** [comment]
Ideally, I would like to have a bunch of examples using codesandbox on the readme to demo these use cases. However, I'm not able to make codesandbox work with svelte components coming from NPM.

**Comment by ValentinH** [comment]
@cpwood I managed to have this library now working on Codesandbox. Would you like to create one to show how you did your custom grid please ? 
You could start from this basic example: https://codesandbox.io/s/svelte-easy-crop-basic-demo-q1005?file=/App.svelte
