### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by ksawery29** [ValentinH/svelte-easy-crop#41]
Hey, I'm trying to use it with typescript, but I'm getting this error:

```ts
Error: Parameter 'e' implicitly has an 'any' type. (ts)
        {cropSize}
        on:cropcomplete={(e) => {
                pixelCrop.set(e.detail.pixels);
```

Will there ever be typescript support?

**Comment by ValentinH** [comment]
I don't think so unless someone wants to contribute it. I have no experience with Svelte using TS.

**Comment by ksawery29** [comment]
> I don't think so unless someone wants to contribute it. I have no experience with Svelte using TS.

I will take look into it then. If it works, I will create a pull request.

**Comment by ValentinH** [comment]
Thanks! I think that a good start would be to expose a d.ts file in the library to type the props.

**Comment by ksawery29** [comment]
@ValentinH I'm getting issues setting up typescript with rollup. Do you mind changing bundler to vite or webpack?

**Comment by ValentinH** [comment]
I'm not attached to Roll-up but we should ensure the library build still generates the same output as before.

**Comment by ksawery29** [comment]
@ValentinH Is typescript compiled and published? I still get error about no type declarations, and on npm page, there isn't typescript icon that indicates project was built with typescript.

example npm project that was built using svelte + typescript:

![image](https://user-images.githubusercontent.com/47505116/215092126-969846a0-75e4-4120-833e-a7b2246b4290.png)

this project:

![image](https://user-images.githubusercontent.com/47505116/215092213-e5dcce8b-0e57-4e20-91a6-eafa502c7275.png)

**Comment by ValentinH** [comment]
OK I see. I wasn't sure if d.ts needed to be published or if Svelte was directly getting them from TS files. I'll have a look.

**Comment by ValentinH** [comment]
@ksawery29 should be good now:
![image](https://user-images.githubusercontent.com/2678610/215213112-74c137b6-97f1-46b0-8f3f-59d50ee09086.png)

please have a look and let me know if you encounter any issue :)

**Comment by ksawery29** [comment]
Yeah, svelte-check isn't throwing any issues about types now
before:

```
Error: Parameter 'e' implicitly has an 'any' type. (ts)
        {cropSize}
        on:cropcomplete={(e) => {
                pixelCrop.set(e.detail.pixels);


====================================
svelte-check found 1 errors, 0 warnings, and 0 hints
```

after:

```
====================================
Loading svelte-check in workspace:
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors, 0 warnings, and 0 hints
```

**Comment by ValentinH** [comment]
Great, I'm closing this then.

i basically changed the whole setup of this project to use `svelte-kit`, now everything is in TS and cleaner. Thanks for having started me on this ^^

I might port other features from https://github.com/ValentinH/react-easy-crop to this version in the coming days, let's see. `react-easy-crop` has grown a lot since I started this `svelte` version 😅
