### ISSUE TITLE
bug: Demos not working

### ISSUE THREAD

**Issue by MentalGear** [ValentinH/svelte-easy-crop#47]
The codesandbox demos do not work anymore. Consider using a static demo?

**Comment by ValentinH** [comment]
Indeed I noticed this recently. What do you mean by a static demo?

**Comment by Raspberry42** [comment]
Could we pay you to have a working demo?

**Comment by MentalGear** [comment]
Basically a static html/js file that doesn't need any external tooling / online IDE service.

**Comment by GimpMaster** [comment]
Demos are still down, but there was an update in January?

The basic demo doesn't work because the CDN image is gone I think.  https://cdn1-www.dogtime.com/assets/uploads/2011/03/puppy-development.jpg is 404

The other demo just never loads

**Comment by ValentinH** [comment]
I missed the previous answers, sorry for this.

I'll have a look to the hosted demos. However, you can clone the repository and follow the development instructions at the bottom of the Readme. This should start a dev demo using Vite.

**Comment by ValentinH** [comment]
I fixed the basic demo: https://codesandbox.io/p/sandbox/svelte-easy-crop-basic-demo-q1005?file=%2FApp.svelte%3A5%2C16

**Comment by ValentinH** [comment]
For the other one, it wasn't belonging to me and it was deleted by the owner (probably due to the recent pricing changes on Codesandbox).
I have no other choices than delete it from the Readme for now.

**Comment by GimpMaster** [comment]
Thank you
