### ISSUE TITLE
Build warning - A11y: <div> with mousedown handler must have an ARIA role

### ISSUE THREAD

**Issue by oscarhermoso** [ValentinH/svelte-easy-crop#48]
Since updating to Svelte 4.0, builds have this warning:

```
/node_modules/svelte-easy-crop/Cropper.svelte:205:0 A11y: <div> with mousedown handler must have an ARIA role
```

I haven't opened up the `svelte-easy-crop` repo yet, but I'm sure this warning will be visible in VS Code:

``` 
A11y: <div> with click, keypress, dragstart, dragend handlers must have an ARIA role (a11y-no-static-element-interactions)
```

I looked at what be a valid role, [best attribute would probably be role="application" ](https://www.darins.page/articles/screen-readers-drag-drop-1#what-were-testing), but this doesn't actually resolve the warning

https://www.w3.org/TR/wai-aria-1.1/#application

**Comment by oscarhermoso** [comment]
I have raised https://github.com/sveltejs/svelte/issues/8943, may need to be fixed first

**Comment by cdcarson** [comment]
Related to https://github.com/sveltejs/svelte/issues/8964

**Comment by WaltzingPenguin** [comment]
This can be resolved by just writing `<!-- svelte-ignore a11y-no-static-element-interactions -->` on the line before.

**Comment by Davidonium** [comment]
This should've been tackled in this PR #49 version 2.0.2
