### ISSUE TITLE
Precise cropping?

### ISSUE THREAD

**Issue by lolmaus** [ValentinH/svelte-easy-crop#56]
My mouse wheel is configured to scroll three lines per tick. <sub>I'm sure I'm not the only one who has it set to 3+ lines, since scrolling by 1–2 lines is painfully slow, especially on large screens.</sub>

As a result, `svelte-easy-crop` crop in very large discrete steps, often missing desired dimensions.

There is the `zoomSpeed` property, but if I tweak it to work for me, it will be messed up for users using different scrolling preferences.

I've looked at other JS cropping libraries, and the absolute majority of them do not have this problem thanks to being able to draw the rectangle with mouse and/or reslize the rectangle by dragging on its edges/corners. Naturally, mouse movement is much more precise than mouse wheel / pinch zooming.

<details>
  <summary>Screenshots from other libraries</summary>
  
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/cf94b200-f6e5-4bed-842d-f2e73fdbb40d)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/b37b3cd9-89b5-44ac-9f09-477c9ea67f9e)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/0a867111-90d7-4346-b940-06da9222d8de)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/31a9c17f-1263-40f0-93b8-e0de9c5f1969)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/edac5a5c-b747-4c4c-b4f8-fdbe3f07dc2e)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/fea991dd-734d-43c5-b613-64041a90da3b)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/f83b2aa9-4c63-4b4d-b08a-b370017270ca)
![image](https://github.com/ValentinH/svelte-easy-crop/assets/200884/8322fc87-acab-47fe-a9b7-d7332695526c)
</details>

**Comment by ValentinH** [comment]
Thanks for opening this issue.

Unfortunately this library doesn't support what you are looking for and it will never support it. Indeed, this is a completely different approach and it doesn't correspond to the interactions this lib was built for.
