### ISSUE TITLE
Support Svelte 5 as a peer dependency

### ISSUE THREAD

**Issue by mhedgpeth** [ValentinH/svelte-easy-crop#58]
Right now this project has a peer dependency of supporting only svelte 4 in the `package.json`:

```json
  "peerDependencies": {
    "svelte": "^4.0.0"
  },
```

This creates a warning when doing an npm install.

I'm using this project just fine with Svelte 5, which supports Svelte 4 component syntax.

While it would be great someday to support that syntax, for now: Would you consider updating the peer dependency?

**Comment by ValentinH** [comment]
Thanks for reporting. It should be fixed on v3.0.1 🚀
