### ISSUE TITLE
How do I get the actual cropped image?

### ISSUE THREAD

**Issue by patrickhener** [ValentinH/svelte-easy-crop#6]
So how do I get the actual cropped image to save it?
Code example would be great.

**Comment by ValentinH** [comment]
Sorry for not answering earlier, for some reasons I didn't have notifications for this repo 🙈

To actually crop the image, you can use canvas operation. There is an example on the parent React version of this project. See this file: https://codesandbox.io/s/q8q1mnr01w?file=/src/cropImage.js

**Comment by ValentinH** [comment]
I'd love to provide a full demo for this but I don't manage to have this library working in Codesandbox for some reasons.
